# Generated by Django 3.1 on 2020-09-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('klass', models.IntegerField(verbose_name='Контактный номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
    ]
