# Generated by Django 3.1 on 2020-09-09 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Introduction',
        ),
    ]
