# Generated by Django 3.1 on 2020-09-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200909_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='klass',
            field=models.CharField(max_length=50, verbose_name='Класс'),
        ),
    ]
