# Generated by Django 3.1 on 2020-09-09 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_showimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showimage',
            options={'verbose_name': 'Изображения', 'verbose_name_plural': 'Альбом'},
        ),
        migrations.RenameField(
            model_name='showimage',
            old_name='image',
            new_name='img',
        ),
    ]
