# Generated by Django 3.1 on 2020-09-09 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20200909_2136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShowImage',
        ),
    ]
