# Generated by Django 3.1 on 2020-09-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_image_recent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recent',
            name='image',
        ),
        migrations.AddField(
            model_name='recent',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='recent',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='recent',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='recent',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='recent',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='recent',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
