# Generated by Django 3.1 on 2020-10-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20200911_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
